# Project name
project: Yatpd 20.5.2

# HTTP version info
httpver: HTTP/1.1

# Default encoding of contents in HTTP requests and responses
contenc: utf-8

# Document root directory and default index file for StaticFile
static:
  docroot: application
  idxfile: index.html

# Document root, upstream and timeout seconds of FastCGIProxy
fastcgi:
  docroot: /absolute/path/to/application/folder
  upstream: localhost:2333
  timeout: 7

# Upstream and timeout seconds of HTTPProxy
http:
  upstream:
    httpbin.local.com: https://httpbin.org
    bing.local.com: https://cn.bing.com
    fish.local.com: https://mo.fish
  timeout: 10

# Log file and content size threshold
logc:
  file: log/main.log
  small: 1024
  large: 4096

# Socket listen host:port pair
listen:
  host: localhost
  port: 80

# Socket read buffer
readbuf:
  first: 2048
  left: 32768

# HTTP status code in use
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
status:
  200: '200 OK'
  303: '303 See Other'
  308: '308 Permanent Redirect'
  400: '400 Bad Request'
  403: '403 Forbidden'
  404: '404 Not Found'
  405: '405 Method Not Allowed'
  413: '413 Payload Too Large'
  500: '500 Internal Server Error'
  501: '501 Not Implemented'
  502: '502 Bad Gateway'
  503: '503 Service Unavailable'
  504: '504 Gateway Timeout'
  505: '505 HTTP Version Not Supported'

# Error Pages' config for HTTP status >= 400
errpage:
  header: 'Content-Type: text/html;charset=UTF-8'
  docroot: errpages/dist/
  file:
    400: HTTP400.html
    401: HTTP401.html
    403: HTTP403.html
    404: HTTP404.html
    500: HTTP500.html
    501: HTTP501.html
    502: HTTP502.html
    503: HTTP503.html
    520: HTTP520.html
    521: HTTP521.html
    533: HTTP533.html

# Allowed and implemented methods
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods
methods:
  StaticFile:
    impl: [GET]
    allow: [GET]
  FastCGIProxy:
    impl: [GET, POST, PUT, DELETE, JSON]
    allow: [GET, HEAD, POST, PUT, DELETE, JSON, OPTIONS]
  HTTPProxy:
    impl: [GET, HEAD, POST, PUT, DELETE, OPTIONS, PATCH]
    allow: [GET, HEAD, POST, PUT, DELETE, CONNECT, OPTIONS, TRACE, PATCH]

# Map from file extension pattern to HTTP MIME type header
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types
mime_type_default: text/plain;charset=UTF-8
mime_type_map:
  "\\.html$": text/html;charset=UTF-8
  "\\.js$": text/javascript;charset=UTF-8
  "\\.css$": text/css;charset=UTF-8
  "\\.ttf$": font/ttf
  "\\.woff$": font/woff
  "\\.(jpg|jpeg|jfif|pjpeg|pjp)$": image/jpeg
  "\\.(png)$": image/png
  "\\.(gif)$": image/gif
  "\\.(svg)$": image/svg+xml
  "\\.(webp)$": image/webp

# URI-based Server/Proxy dispatch
serpro_default: StaticFile
serpro_class_map:
  "\\.(html|js|css|png|ttf)$": StaticFile
  "\\.php$": FastCGIProxy
  "^/http_pass": HTTPProxy
class_file_map:
  StaticFile: static_file
  FastCGIProxy: fastcgi_proxy
  HTTPProxy: http_proxy
